### PR TITLE
wrong pointer refer to an array

### PR DESCRIPTION
**Pull request by johnnyleeRH**
I think vsp shall point to the element of vrs array, if not update, segment fault happend in my local place.

### CODE REVIEW

**Comment by troian** [comment]
Does not seem to be a fix. At least unwind does not work on Cortex-M4
**Origin**
```
	backtrace:
		| frame # |  address  | function name
		|---------|-----------|--------------
		#      0    0x8011706   hardfault_process
		#      1    0x8012a20   main
		#      2    0x8012c28   _Z8pre_mainv
		#      3    0x800e0fc   osThreadExit
		#      4    0x80183f4   unknown
```

With your fix
```
	backtrace:
		| frame # |  address  | function name
		|---------|-----------|--------------
		#      0    0x8011706   hardfault_process
		#      1    0x0   <reached end of unwind table>
```

**Comment by johnnyleeRH** [comment]
@troian thanks for your infomation, at my HW HISI platform, the backtrace run crashed.

**Comment by sgstreet** [comment]
Sorry for the delayed response.  Can you post a test sample demonstrating the problem?  Which compiler are you using?  Which chip?  With or without hard FPU?

**Comment by johnnyleeRH** [comment]
@sgstreet HW hisi3519, just run the raw backtrace demo, and it crashed.
arm linux, arm-hisiv500-linux toolchain, without FPU.

**Comment by sgstreet** [comment]
Closing this, I you are still having a problem can you file a new issues?

**Pull request closed without merging**
